services:
  slideshow:
    image: slideshow:latest
    ports:
      - "7070:8000"
    volumes:
      - /home/iain/data/photo/Pictures-Slideshows/family:/slideshows
    restart: unless-stopped
    environment:
      PICTURES_BASE: /slideshows
