[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
