name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Dist
        run: |
          cargo install --locked trunk
          cargo xtask dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: slideshow-linux
          path: output

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --release

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Dist
        run: |
          cargo install --locked trunk
          cargo xtask dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: slideshow-windows
          path: output

  test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --release
